---
title       : R and Google Visualization
subtitle    : 
author      : Daniel Fischer
job         : Natural Resources Institute Finland, Green Technology
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## Slide 2

---

## This is the next test!!!

sdfs  lkdsjfldskj f

s dlökjs ölkjsd öllkds j


sdl sdök jfösldkj ösldj

---
## A Simple Plot

 ```{r simple-plot, fig.height = 6, fig.align = 'center', message = F}
 require(ggplot2)
 qplot(wt, mpg, data = mtcars)
 ```

---

## MotionPlot

 ```{r results = 'asis', commment = NA, message = F, echo = F}
 require(googleVis)
 M1 <- gvisMotionChart(Fruits, idvar="Fruit", timevar="Year")
 print(M1, tag = 'chart')
 ```


